[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "gcc",
  "glib",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "libffi",
  "shared-mime-info",
  "wkhtmltopdf"
]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "playwright install chromium"
]

[phases.start]
cmd = "python -m flask --app app db upgrade && gunicorn app:app --bind 0.0.0.0:$PORT"
