"""Add grade_point and pass_fail to StudentCourseGrade

Revision ID: 0528bde5114b
Revises: 7120c7262db7
Create Date: 2026-02-02 16:23:05.441854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0528bde5114b'
down_revision = '7120c7262db7'
branch_labels = None
depends_on = None


def upgrade():
        connection = op.get_bind()
    inspector = sa.inspect(connection)
    table_name = 'student_course_grade'
    if table_name not in inspector.get_table_names():
        return

    columns = {column['name'] for column in inspector.get_columns(table_name)}

    if connection.dialect.name == 'postgresql':
        if 'grade_point' not in columns:
            op.execute(sa.text(
                'ALTER TABLE student_course_grade ADD COLUMN IF NOT EXISTS '
                'grade_point FLOAT'
            ))
        if 'pass_fail' not in columns:
            op.execute(sa.text(
                'ALTER TABLE student_course_grade ADD COLUMN IF NOT EXISTS '
                'pass_fail VARCHAR(10)'
            ))
        return

    with op.batch_alter_table(table_name, schema=None) as batch_op:
        if 'grade_point' not in columns:
            batch_op.add_column(sa.Column('grade_point', sa.Float(), nullable=True))
        if 'pass_fail' not in columns:
            batch_op.add_column(sa.Column('pass_fail', sa.String(length=10), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course_grade', schema=None) as batch_op:
        batch_op.drop_column('pass_fail')
        batch_op.drop_column('grade_point')

    # ### end Alembic commands ###
