"""Add notification system

Revision ID: 7120c7262db7
Revises: 
Create Date: 2026-02-02 05:30:03.303810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7120c7262db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    table_name = 'notifications'
    existing_tables = inspector.get_table_names()

    if table_name not in existing_tables:
        return

    columns = {column['name'] for column in inspector.get_columns(table_name)}
    indexes = {index['name'] for index in inspector.get_indexes(table_name)}

    if connection.dialect.name == 'postgresql':
        if 'priority' not in columns:
            op.execute(sa.text(
                'ALTER TABLE notifications ADD COLUMN IF NOT EXISTS '
                'priority VARCHAR(20)'
            ))
        if 'is_archived' not in columns:
            op.execute(sa.text(
                'ALTER TABLE notifications ADD COLUMN IF NOT EXISTS '
                'is_archived BOOLEAN'
            ))
        if 'ix_notifications_created_at' not in indexes and 'created_at' in columns:
            op.execute(sa.text(
                'CREATE INDEX IF NOT EXISTS ix_notifications_created_at '
                'ON notifications (created_at)'
            ))
        if 'ix_notifications_type' not in indexes and 'type' in columns:
            op.execute(sa.text(
                'CREATE INDEX IF NOT EXISTS ix_notifications_type '
                'ON notifications (type)'
            ))
        return

    with op.batch_alter_table(table_name, schema=None) as batch_op:
        if 'priority' not in columns:
            batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        if 'is_archived' not in columns:
            batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    if 'ix_notifications_created_at' not in indexes and 'created_at' in columns:
        op.create_index('ix_notifications_created_at', table_name, ['created_at'], unique=False)
    if 'ix_notifications_type' not in indexes and 'type' in columns:
        op.create_index('ix_notifications_type', table_name, ['type'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_column('is_archived')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
